export const ERROR_CODES = {
  // Generic
  SERVER_ERROR: "SERVER_ERROR",

  // User / Room - Name DONE
  NAME_EMPTY: "NAME_EMPTY",
  USER_LENGTH: "USER_LENGTH",
  NAME_TAKEN: "NAME_TAKEN",
  ROOM_LENGTH: "ROOM_LENGTH",

  // Room
  ROOM_NOT_FOUND: "ROOM_NOT_FOUND",
  ROOM_FULL: "ROOM_FULL",
  NOT_IN_ROOM: "NOT_IN_ROOM",
  NOT_ADMIN: "NOT_ADMIN",
  NOT_ENOUGH_PLAYERS: "NOT_ENOUGH_PLAYERS",
  CAPACITY_CONFLICT: "CAPACITY_CONFLICT",
  PLAYER_NOT_FOUND: "PLAYER_NOT_FOUND",

  // Game
  GAME_NOT_FOUND: "GAME_NOT_FOUND",
  TURN_NOT_FOUND: "TURN_NOT_FOUND",
  NOT_YOUR_TURN: "NOT_YOUR_TURN",

  // Card play
  CARD_NOT_FOUND: "CARD_NOT_FOUND",
  COLOR_MISSING: "COLOR_MISSING",
  INVALID_COLOR: "INVALID_COLOR",
  HAS_TO_BE_NUMBER: "HAS_TO_BE_NUMBER",
  INVALID_MOVE: "INVALID_MOVE",

  // Turn actions
  ALREADY_DRAW: "ALREADY_DRAW",
  ALREADY_PLAYED: "ALREADY_PLAYED",
  TURN_INCOMPLETE: "TURN_INCOMPLETE",
  EFFECT_ON: "EFFECT_ON",

  // UNO
  INVALID_UNO_CALL: "INVALID_UNO_CALL",
  UNO_ALREADY_CALLED: "UNO_ALREADY_CALLED",

  // Cut
  INVALID_CUT_CALL: "INVALID_CUT_CALL",
  CAN_NOT_SELF_CUT: "CAN_NOT_SELF_CUT",
} as const;

export type ErrorCode =
  (typeof ERROR_CODES)[keyof typeof ERROR_CODES];